### PR TITLE
Onboarding Screen

### PR DESCRIPTION
**Pull request by the0neyouseek**
This PR is related to this issue: #676

### What's new
- ✨ Add an onboarding screen (only appear on first launch)
- 🇫🇷 French translations for the new onboarding screen
- 🛠 Reorganize AppDelegate a bit
- 🛠 Move View Controllers into folders

### Tests
I've tested the onboarding screen on both small and large screen, HiDPI and normal res, light and dark mode.

If you want to test the PR you can save your preferences located here:
```
~/Library/Preferences/me.guillaumeb.MonitorControl.plist
```
and run this command to reset your current preferences (where the app check to know if it was started once)
```
$ defaults delete me.guillaumeb.MonitorControl
```
before the launching the project in XCode. 

### What's left to do
All current translations beside French & English (for the new onboarding) are missing for now.
If you want to help with translations, please read the opening post of this discussion: #637

- [ ] Translations :
	- [ ] Spanish
	- [ ] German
	- [ ] Hungarian
	- [ ] Italian
	- [ ] Korean
	- [ ] Dutch
	- [ ] Portuguese (Brazil)
	- [ ] Turkish
	- [ ] Chinese, Simplified
	- [ ] Chinese, Traditional (Taïwan)
- [x] I also forgot to translate the keyboard screenshot part (I'll get to it asap)

### CODE REVIEW

**Review by waydabber — DISMISSED** [review]
Everything looks good! Good job!

**Comment by the0neyouseek** [comment]
I think i'm done with this PR, feel free to add commits if you want to maybe add some translations @waydabber @JoniVR

**Comment by waydabber** [comment]
He @the0neyouseek - I have an issue - something seems to be off.

Screen Shot 2022-01-23 at 16 58 46

Steps to reproduce:

- delete app defaults `defaults delete me.guillaumeb.MonitorControl`
- pull the latest code from `feat/onboarding`
- build&run

The onboarding screen does not pop up now, but a complaint about permissions do (when security permissions are not granted to the app).

**Comment by the0neyouseek** [comment]
That's weird. Maybe I messed something up, I'll look into it

**Review by waydabber — APPROVED** [review]
Works perfectly now! :)

**Comment by waydabber** [comment]
Hey @the0neyouseek - is this PR now done or you still working on it? Shouldn't it be merged? :)

**Comment by the0neyouseek** [comment]
Done for me :) You can merge it

**Pull request merged**
