### PR TITLE
Added Slovak language thanks to @Svec-Tomas

### PR DESCRIPTION
**Pull request by waydabber**
Thank you @Svec-Tomas!

https://github.com/MonitorControl/MonitorControl/discussions/637#discussioncomment-7931745

### CODE REVIEW

**Review by the0neyouseek — APPROVED** [review]
LGTM

**Comment by Svec-Tomas** [comment]
Thanks a lot for implementing Slovak language! When do you think a new version including Slovak language will be available for a download? Thanks!

Tomáš Švec

**Comment by waydabber** [comment]
Hi @Svec-Tomas - not sure to be honest, there are no future official feature releases planned but there might still be some service or compatibility releases and those should include the latest translations as well.

As an alternative you can build a version of the app in XCode if you clone the app.

**Comment by Svec-Tomas** [comment]
Then it would be really fair from you to remove it from the app description and not to ask for more translations, don't you think?

Localizations

Also to mention it here as well:

https://github.com/MonitorControl/MonitorControl/discussions/637

It is just really frustrating that someone takes a lot of time and effort to localise a great app (no, I am not doing this for myself!), so others can also use it in their native language. There's nothing worse than finding out I've been doing useless work!

I wanted to eventually translate BetterDisplay 2 as well, but I will just pass really. It can not be really that time consuming to release a new version including my translation, or is it really that much work?

**Comment by waydabber** [comment]
You are right of course, sorry about all this. I added a note to #637!

**Comment by waydabber** [comment]
Note: due to some issues with various permissions and how developer accounts are working I am unable to produce a properly signed version of MonitorControl for distribution but you might make a plea to @JoniVR to drop a 4.2.1 update with the latest translation included - I am sure if he has the time will do it! I understand your frustration and would be sad to see your contribution to be in vain @Svec-Tomas.

**Comment by Svec-Tomas** [comment]
@JoniVR Would you be so kind and will you release a new version of Monitor Control with my translation included and also other improvements (updates) that were gathered since the last release, please? Thanks a lot in advance.

**Comment by Svec-Tomas** [comment]
I am sorry to revive this again, but one and a half month passed and nothing happened, not even a reply from anyone. I was so excited to work on the translation to make Monitor Control available in my native language and then so disappointed that I worked on something, that is basically a dead product, just to find out, that I should have worked on Better Display instead. But after all this, this is something I will not going through again. Very disappointed and definitely will not recommend Monitor Control or other products again.

**Comment by waydabber** [comment]
Hi @Svec-Tomas - Please don't take it personally. Of course I understand your sentiment, sorry about all this. 😞

**Pull request merged**
