### PR TITLE
Add some zh-Hans translations 

### PR DESCRIPTION
**Pull request by gtn1024**

### CODE REVIEW

**Comment by JoniVR** [comment]
Hi @gtn1024, thanks for the updates, however, you seem to have missed some lines, was this intentional?

**Comment by gtn1024** [comment]
> Hi @gtn1024, thanks for the updates, however, you seem to have missed some lines, was this intentional?

Oh, yeah.

Some lines were out of my capacity.

**Comment by long2ice** [comment]
可以使用Google翻译一下大概意思

**Review by JoniVR — APPROVED** [review]

**Comment by JoniVR** [comment]
Thanks @gtn1024!

**Pull request merged**
