### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by carbongo**
I translated everything I could find

### CODE REVIEW

**Comment by waydabber** [comment]
Hi there, there is a third file to translate: 

https://github.com/MonitorControl/MonitorControl/blob/master/MonitorControl/Support/ru.lproj/Localizable.strings

Can you add that as well? :) Thank you!

**Comment by carbongo** [comment]
> Hi there, there is a third file to translate:
> 
> https://github.com/MonitorControl/MonitorControl/blob/master/MonitorControl/Support/ru.lproj/Localizable.strings
> 
> Can you add that as well? :) Thank you!

Sure! No problem

**Comment by carbongo** [comment]
@waydabber done! ;)

**Review by waydabber — APPROVED** [review]
Looks good to me! :)

**Pull request merged**
