### PR TITLE
Update Chinese (Traditional, Taiwan) translation

### PR DESCRIPTION
**Pull request by stiiveo**
Add missing translations of Chinese (Traditional, Taiwan) in v4.0.0 and edit previous ones in more local fashion.

### CODE REVIEW

**Comment by waydabber** [comment]
Hi @stiiveo - I see that you updated [Localizable.strings](https://github.com/MonitorControl/MonitorControl/blob/master/MonitorControl/UI/zh-Hans.lproj/Localizable.strings). Can you update [Main.strings](https://github.com/MonitorControl/MonitorControl/blob/master/MonitorControl/UI/zh-Hans.lproj/Main.strings) as well in order to make the translation complete? I'd wait with the merge until the whole translation is completed.

Thank you for your contribution, it is highly appreciated! :)

**Comment by waydabber** [comment]
Here is a quick tutorial regarding translation which might help:

https://github.com/MonitorControl/MonitorControl/discussions/637

**Comment by stiiveo** [comment]
Thanks for the tutorial @waydabber. I didn't see that one until now. ;)
I'll make a new PR once it's fully translated.

I did encounter a runtime error while attempting to build and test it.
The error code is as followed:

`dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
Referenced from: /Users/jasonou/Library/Developer/Xcode/DerivedData/MonitorControl-giuuriltaxeyhialiwwxjivzmdop/Build/Products/Debug/MonitorControl.app/Contents/MacOS/MonitorControl
Reason: no suitable image found.  Did find:
/Users/jasonou/Library/Developer/Xcode/DerivedData/MonitorControl-giuuriltaxeyhialiwwxjivzmdop/Build/Products/Debug/Sparkle.framework/Versions/A/Sparkle: code signature in (/Users/jasonou/Library/Developer/Xcode/DerivedData/MonitorControl-giuuriltaxeyhialiwwxjivzmdop/Build/Products/Debug/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
/Users/jasonou/Library/Developer/Xcode/DerivedData/MonitorControl-giuuriltaxeyhialiwwxjivzmdop/Build/Products/Debug/MonitorControl.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: code signature in (/Users/jasonou/Library/Developer/Xcode/DerivedData/MonitorControl-giuuriltaxeyhialiwwxjivzmdop/Build/Products/Debug/MonitorControl.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)`

It seems that it has to do with the auto–updating framework **Sparkle**. Is there any way to get around this? As of now I can only build but not run it, which makes debugging impossible.

Thanks in advance! :)

**Comment by waydabber** [comment]
Hi @stiiveo 

yes, you need to change the Team and Signing Certificate settings for Sparkle and specify something in order to make it work. Do it both for `MonitorControl` and `MonitorControlHelper`.

Screen Shot 2021-10-01 at 11 52 53

**Review by waydabber — APPROVED** [review]
I don't speak Chinese but the files look ok to me. :) Thank you!

**Comment by waydabber** [comment]
Thank you @stiiveo for your help!

**Pull request merged**
