### PR TITLE
Updated screenshot

### PR DESCRIPTION
**Pull request by waydabber**

### CODE REVIEW

**Comment by JoniVR** [comment]
Question, can you round off the corner again like you did on v3.0.0? Not sure how you did it (picture itself or css) but it looked really slick imo.

**Comment by waydabber** [comment]
> Question, can you round off the corners again like you did on v3.0.0? Not sure how you did it (picture itself or css) but it looked really slick imo.

Yes of course

**Comment by waydabber** [comment]
Rounded corners. I use Affinity Designer.

**Comment by waydabber** [comment]
I mean Affinity Photo for this one.

**Comment by JoniVR** [comment]
neat

**Review by JoniVR — APPROVED** [review]

**Pull request merged**
