### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by ozkanozcan**

### CODE REVIEW

**Review by iamalperen — APPROVED** [review]

**Comment by waydabber** [comment]
Hey @ozkanozcan @iamalperen - there are conflicts with master. Can you guys help me resolving these? Thank you!

**Comment by waydabber** [comment]
I think the conflicts are due to https://github.com/MonitorControl/MonitorControl/pull/663 by @mennan. The best course of action would be go through the conflicting entries and choose whichever you feel is the best. Since I don't speak Turkish, I cannot reconcile the conflicts but once these are resolved, I'll approve the PR and note your contribution to the Turkish translation.

Thank you all!

**Comment by waydabber** [comment]
Hi all, question: will there be any activity on this? The conflicts must be resolved. Should I close this PR until that time? Please let me know how do you wish me to proceed with this. Thank you!

**Comment by waydabber** [comment]
I'll close this PR for now but please let me know if you want me to change course with this. Thank you all for your contribution and I am sorry that it seems two Turkish translations were being worked on at the same time, I know this can be frustrating.

**Pull request closed without merging**
