### PR TITLE
Some minor fixes and changes

### PR DESCRIPTION
**Pull request by waydabber**
- Fixes clipping English text when gamma control is forced.
- Fixes clipping view in Displays with Chinese text.
- Set relevant options to disabled when keyboard control is disabled.
- Added Command+Q shortcut in menu when it is in standard text mode (not icon mode).
- Gearshape icon is used for preferences + stands a little bit apart to help user focus.
- Make preferences more spacious + more room for verbose languages
- Fixed dutch version clipping issues
- Added beta channel update backend

### CODE REVIEW

**Comment by JoniVR** [comment]
I'll check this out tomorrow, perhaps might be a good time for beta 2 as well (after this PR)?

**Comment by waydabber** [comment]
> I'll check this out tomorrow, perhaps might be a good time for beta 2 as well (after this PR)?

Ok. We can do a beta2 or an RC which could be classified not as pre-release but release (with a note that the current stable release 3.1.1 is available as well for those who encounter issues) - maybe that way we'd be able to gather responses and translations faster.

**Comment by JoniVR** [comment]
Should I wait a bit with reviewing this until we've clarified a solution for clipping etc? 

> Ok. We can do a beta2 or an RC which could be classified not as pre-release but release (with a note that the current stable release 3.1.1 is available as well for those who encounter issues) - maybe that way we'd be able to gather responses and translations faster.

I think the lack of participation in betas is mostly due to v3.0.0 already working for Apple Silicon users and thus less people bothering to try it due to already having a working version. 

What we could also do is posting in the Apple Silicon thread asking for beta testers, since lots of people were subscribed to it. We had plenty of participation on v3.0.0 betas so I doubt visibility of the releases is the issue.

Most of the v4.0.0 seems stable though so I doubt we'll be needing many beta releases. Perhaps the UI  might need some minor tweaking here and there. I'd also like to make sure Sparkle updates work properly with next beta.

**Comment by waydabber** [comment]
I think this could be merged as it is. Regarding beta2 vs RC I trust in your judgement in determining the best course of action. A middle way solution might be to release it as beta2 but do not tag it as pre-release as it will show up on the opening screen at least (from the beta designation it will be obvious that it is a beta anyway).

Asking Apple Silicon folks is a great idea, once beta2 is out, we'll post a request on that thread.

Questions:
- Will the next beta release update with Sparkle?
- Should we add an advanced option to select channel (default/beta)?

**Comment by JoniVR** [comment]
> Will the next beta release update with Sparkle?

Yes, I want to use the next beta to test out if Sparkle updates work as expected, though I can also test this out using a separate branch, which I'm planning on doing before releasing the beta.

> Should we add an advanced option to select channel (default/beta)?

In the future yes, though right now, I'd work without channels, only beta versions have Sparkle, so after beta releases, we'll just add regular releases in the channel and no actions from the user will need to be taken. Beta users will automatically get upgraded to stable this way.

 If we were to do more beta's in the future, then we could still setup channels.

**Review by JoniVR — DISMISSED** [review]

**Comment by waydabber** [comment]
> In the future yes, though right now, I'd work without channels, only beta versions have Sparkle, so after beta releases, we'll just add regular releases in the channel and no actions from the user will need to be taken. Beta users will automatically get upgraded to stable this way.

> If we were to do more beta's in the future, then we could still setup channels.

Ok! I added the backend code for beta channel support but it is not exposed in Preferences/General.

**Comment by waydabber** [comment]
Ooops. The branch was updated and I did a pull the source file I added was somehow deleted in the process lol.

**Comment by waydabber** [comment]
Or not. It was just removed from the project I see as I pulled a new xcode settings file. Let me fix it. :)

**Comment by waydabber** [comment]
Ok, it should be fixed. If you find everything ok, then this can be merged. Thank you!

**Review by JoniVR — APPROVED** [review]

**Pull request merged**
