### PR TITLE
Update localization(Taiwan)

### PR DESCRIPTION
**Pull request by dororojames**

### CODE REVIEW

**Comment by waydabber** [comment]
Hey @dororojames - are `Taiwan` and `Traditional, Taiwan` submitted by @stiiveo different? It seems both merges use the same language code. I can add both but only if they are different. I see these options but I am unsure which one to recommend:

Screen Shot 2021-10-01 at 20 18 30

If the two translations are the same, then I think the best course of action is to go through @stiiveo's translation (which is by this time merged to the master) as a proofreader and amend things that you think should be amended.

**Thank you for your contribution!**

**Comment by dororojames** [comment]
Hello, I think they are same language.
Actually, I just updated some code and complete the untranslated code from the current master version.


James Chan

> Istvan T. ***@***.***> 於 2021年10月2日 上午2:25 寫道：
> If the two translations are the same, then I think the best course of action is to go through @stiiveo's translation (which is by this time merged to the master) as a proofreader and amend things that you think should be amended.

**Comment by waydabber** [comment]
> Hello, I think they are same language. Actually, I just updated some code and complete the untranslated code from the current master version. James Chan
> […](#)

It seems like you two basically worked on it at the same time. I really commend both of you, it is really inspiring to see how not one, but two of you rush to do a translation for your countrymen - this is an example for all the others! I recommend you to go through the other translation then since that was the one with earlier PR number and feel free to improve it if you spot anything you can make better - as that will solve the conflict issue.

Thank you again both of you @dororojames and @stiiveo!

**Comment by stiiveo** [comment]
🤯
What's the probability of having two guys working on the same translation and both submitted the work at the same time? Small world huh?🤝 I guess it just demonstrated how popular this App really is. Kudos to @waydabber and all of the contributors!

I briefly looked into @dororojames 's work and found some of the translations are actually better than mine. As mentioned by @waydabber , feel free to improve the already merged one. Or if it's ok, I can try to improve the current version by adopting some of your translations. Please let me know.

**Comment by dororojames** [comment]
@stiiveo Thank you for your comment.Sure you can take any translation from my side if you think its better👌.

**Comment by waydabber** [comment]
Please by all means improve the translation as you wish. I can't decide on this since I don't speak the language, but if any of you post a new Pull Request on further improvements I'll of course approve it! :) Thank you!

**Pull request closed without merging**
