### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by JoniVR**
Added updates to French translation files from #608 and ran the build scripts, which updated some other files.

### CODE REVIEW

**Review by waydabber — APPROVED** [review]
I don't speak French but it looks nice. 👍

**Comment by JoniVR** [comment]
Me neither.. well.. a little since we're required to know some French in the Dutch part of Belgium 😅

**Comment by the0neyouseek** [comment]
I do and it looks good ;) don't worry

**Comment by waydabber** [comment]
Hey, don't work on 4.0.0 yet as it is constantly changing. I'll let everybody know if its time to translate here: https://github.com/MonitorControl/MonitorControl/discussions/596

**Comment by waydabber** [comment]
However there is an other French translation here: https://github.com/MonitorControl/MonitorControl/pull/611

I don't understand what's the difference and why is there two. :) Maybe somebody with French knowledge can help with this.

**Pull request merged**
