### PR TITLE
Set archs to standard for releases

### PR DESCRIPTION
**Pull request by JoniVR**
Apparently we forgot to change this 😅

### CODE REVIEW

**Review by waydabber — APPROVED** [review]

**Comment by JoniVR** [comment]
Just an FYI for the future, when merging, it's usually preferable to pick "Squash" merge (aka combine commits into one you can rename), however in this case it wasn't really necessary since it was just one commit :)

**Comment by JoniVR** [comment]
If it's just one or two clean commits you can also pick Rebase merge, that just puts all the commits directly on top of master without merge commit.

**Comment by waydabber** [comment]
Ok, I'll do that next time, sorry! :) This is only to make commit history nicer?

**Comment by JoniVR** [comment]
No big deal 🙂 yeah it's mostly to make the history cleaner (easier to read changes) and to prevent random commits from polluting the history

**Pull request merged**
