### PR TITLE
DDC support for high-end M2 (Pro/Max/Ultra) systems

### PR DESCRIPTION
**Pull request by waydabber**
Added DDC support for high-end M2 (Pro/Max/Ultra) systems using displays connected via USB-C/ThunderBolt/DisplayPort and HDMI.

(note: somebody with an M2 Pro/Max/Ultra Mac should test it, I am still on M1 :))

### CODE REVIEW

**Comment by JerryZhangZZY** [comment]
Could you post a compiled .dmg file so that I can test it?

**Comment by waydabber** [comment]
Sure. This build is unsigned and not notarized so you'll need to manually allow it to run under Security&Privacy. Let me know if you did try it so I can delete this.

[MonitorControl.zip](https://github.com/MonitorControl/MonitorControl/files/12217789/MonitorControl.zip)

**Comment by JerryZhangZZY** [comment]
> Sure. This build is unsigned and not notarized so you'll need to manually allow it to run under Security&Privacy. Let me know if you did try it so I can delete this.
> 
> [MonitorControl.zip](https://github.com/MonitorControl/MonitorControl/files/12217789/MonitorControl.zip)

DDC works perfectly on M2 Pro, nicely done mate!

**Comment by waydabber** [comment]
Great! Thanks for the feedback!

**Comment by nic** [comment]
Amazing! DDC works sweetly fine on M2 Ultra. Awesome job, dude! 🤩

**Comment by devantler** [comment]
Awesome work! 😃 Sadly, I was not able to make this work. The volume is not affected when I change the volume slider with the Apple keys or the slider in MonitorControl.

image

- LG C2 connected on HDMI_2 (can this affect the logic?)
- The build has been allowed under Security&Policy>Accessiblity

Can it be related to running Sonoma?

**Comment by alexforster** [comment]
Worked on my new MBP `Mac14,9` driving two LG `27UN880-B` monitors.

**Comment by devantler** [comment]
> Sadly the LG C2 (as most TVs) does not support DDC. :(

Ah damn. Back to proxy-audio-device for me then 🙂

**Review by the0neyouseek — APPROVED** [review]
🙌 LGTM ! Thank you so much for the PR, everything looks good as far as I can see !

**Comment by waydabber** [comment]
Thanks @the0neyouseek ! :)

**Comment by pakal-org** [comment]
Can we expect a release soon ?

Thanks

**Comment by waydabber** [comment]
> Can we expect a release soon ?
> 
> Thanks

I am not sure, I can't sign a build for release, it depends on the team. You can of course build a version using XCode anytime.

**Comment by pakal-org** [comment]
I thought that project was dead...
I can wait a little more :)

**Comment by waydabber** [comment]
@pakal-org, the project is not dead, just in a bit slow-to-respond mode...

Note: if you don't want to build a release yourself, you can try BetterDisplay meanwhile as it has DDC brightness control for the M2 Pro for free - try https://github.com/waydabber/BetterDisplay/releases/tag/v2.0.6-pre-release

**Comment by waydabber** [comment]
Yes, I can understand that. :)

**Comment by dellhem** [comment]
What a flex! Fixing the competition's issues 😆 Great work, @waydabber 😘

**Comment by cgull** [comment]
Thanks, @waydabber -- this works fine for me on a 14" M2 MBP Mac14,5 and two LG LS27A800U monitors on USB-C cables, after building e038b89f647e839fa7f8afafdb991ceb7ece59c0.

Maintainers, what blocks generating a new release?

**Comment by JoniVR** [comment]
We'll do a new release with this fix soon.

**Comment by kaeferfreund** [comment]
I have compiled it on my own and it works like a charm, very stable so far :)

**Comment by lestmak** [comment]
On a Mac Mini M2 Pro with an LG UltraWide Monitor 38WN95C-W. Working beautifully and perfectly. Thanks for this!

**Comment by frunika** [comment]
Work's perfect. Thanks! :)

**Pull request merged**
