### PR TITLE
Fix library validation causing crash when debugging due to Sparkle

### PR DESCRIPTION
**Pull request by JoniVR**
Please test if this fixes the issue as it did for me. This is supposed to fix the issue where we have to set Signing every time for it to not crash :)

### CODE REVIEW

**Comment by waydabber** [comment]
But... but you changed 'Quit appliation'. I was trying to reform the English language with that and now my plans are ruined! :)

**Comment by JoniVR** [comment]
lol I saw that change in the comments of my first commit and I was like... waaaait a minute... 😂

**Comment by waydabber** [comment]
Nice, it does seem to work! This change will help folks who get into contributing to the project and they won't be discouraged that the first thing they is a long list of errors. :)

An other related issue is that if there is no signing, Accessibility Access always complains and I have to re-add the app every time to Privacy/Accessibility. Do you have this behavior?

**Review by waydabber — DISMISSED** [review]

**Comment by waydabber** [comment]
Something happened with this:

Screen Shot 2021-10-01 at 21 40 33

**Comment by JoniVR** [comment]
> Nice, it does seem to work! This change will help folks who get into contributing to the project and they won't be discouraged that the first thing they is a long list of errors. :)

I agree, it was an issue that I wanted to get tackled asap as it makes it harder for people to contribute, and it annoyed the hell out of me.

> An other related issue is that if there is no signing, Accessibility Access always complains and I have to re-add the app every time to Privacy/Accessibility. Do you have this behavior?

I haven't noticed it, I'll do another full clean and test everything again.

**Comment by JoniVR** [comment]
> Something happened with this:

I see, it seems like it doesn't work anymore, perhaps that's a side effect, let me look into it.

**Comment by JoniVR** [comment]
Side note: these docs explain what it does and why:
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation

**Comment by waydabber** [comment]
> > An other related issue is that if there is no signing, Accessibility Access always complains and I have to re-add the app every time to Privacy/Accessibility. Do you have this behavior?
> 
> I haven't noticed it, I'll do another full clean and test everything again.

This started happening only after I did a `tccutil reset All` in terminal (this resets the privacy database) a few weeks ago. But this is the default behavior as well as I tested it on a cleanly installed Big Sur system as well. I think something changed in macOS and since that time after a reset the default behavior is if the app is not signed, then every time the app version or hash is changed, you have to whitelist the app again in Privacy. This makes debuggin super cumbersome.

**Comment by waydabber** [comment]
> > Something happened with this:
> 
> I see, it seems like it doesn't work anymore, perhaps that's a side effect, let me look into it.

Ohh, and that as well. I was just pointing out that the frame shifted somehow, but you are right, it is actually not working anymore which is obviously a more serious issue. :)

**Comment by JoniVR** [comment]
The thing is, this only happens during debug, so it doesn't cause an issue for releases, but it's still a pretty big issue even during development..

**Comment by JoniVR** [comment]
Ugh, I'm going to leave this open and look into it some more another time. Seems like the issue is that Sparkle isn't signed with the same signature, which then causes Library Validation/Hardened Runtime to block it. 

From what I can tell, options are:
* Embed as Framework (not through SPM?) and re-sign with ad-hoc signature during development (not sure if possible)
* Disable Library Validation (causes side effects)
* ...?

**Comment by JoniVR** [comment]
I'm very confused right now, I reverted all storyboard and entitlement changes, and the label misalignment issue is still there (everything else works fine), so is it really going to be the typo fix causing it??

**Comment by JoniVR** [comment]
Can you check if master has this same issue? For me the current release build also has the misalignment issue, and the shortcuts do work in this fix, I just forgot that you still need to use a modifier key for them to work lol

**Comment by waydabber** [comment]
> I'm very confused right now, I reverted all storyboard and entitlement changes, and the label misalignment issue is still there (everything else works fine), so is it really going to be the typo fix causing it??

**Comment by waydabber** [comment]
> I'm very confused right now, I reverted all storyboard and entitlement changes, and the label misalignment issue is still there (everything else works fine), so is it really going to be the typo fix causing it??

Yes, master has this as well. I think somehow it just moved away a bit. IB sometimes does funny things like this. As far as I see the released beta looks like this as well. No biggie. :)

**Comment by JoniVR** [comment]
Alright, thought I was going crazy there for a sec 😁 so does this introduce any other issues then? You mentioned the Privacy/Accessibility reset, but I'm not noticing that? I am noticing the "incompatible preferences" popup every once in a while but I don't think that's caused by this change either.

**Comment by waydabber** [comment]
No, that is an entirely different issue but necessitates signing (at least for me) anyway otherwise I can't really debug or use the app only if I add it to Privacy/Accessibility every time which is more cumbersome than just enable signing and then disable it if I want to do a pull request (as with signing xcodebuild fails in the repo).

**Comment by waydabber** [comment]
Incompatible preferences happens if you revert the version to a previous build from the one you ran last time. The app does not allow itself to downgrade without preferences reset.

**Comment by waydabber** [comment]
The Privacy/Accessibility issue with unsigned build will probably happen if you do a `tccutil reset All` - but I don't recommend it as this resets all privacy settings to its defaults and you'll probably have this issue going forward with no way to fix it. I think Apple changed something in one of it security updates which takes effect on new installs or upon resetting defaults.

**Comment by JoniVR** [comment]
Hmm I see, perhaps what could be a quick & dirty workaround is creating a git .patch file from when you set your signing settings, and then setup a `pre-commit` hook which removes the .patch, pretty sure that would automate the setting for you, though it does require some setup.

**Comment by waydabber** [comment]
> Hmm I see, perhaps what could be a quick & dirty workaround is creating a git .patch file from when you set your signing settings, and then setup a `pre-commit` hook which removes the .patch, pretty sure that would automate the setting for you, though it does require some setup.
> 
> Another alternative is indeed a .gitignored file with these settings but isn't very "newbie-friendly" for people who want to contribute.

This really was an issue only when I wanted to do a pull request as my signing interfered with the xcodebuild configured in the repo. But it's not happening that often so I can live with it. :) Disabling the signing issue for Sparkle would be more important for other contributors who try to build the app for themselves. But I made a [Q&A entry about this](https://github.com/MonitorControl/MonitorControl/discussions/638) so hopefully that will help.

**Comment by waydabber** [comment]
Until the sparkle signing issue is resolved (if it can be easily resolved) I'll add a separate PR for the layout and quit application problem as it bugs me that the master is now this way. :)

**Comment by JoniVR** [comment]
Alright, do we still want to merge this? (as it does alleviate the problem for new users)

**Comment by waydabber** [comment]
> Alright, do we still want to merge this? (as it does alleviate the problem for new users)

We can. Maybe I misunderstood, I thought you want to hold off with it because it breaks shortcuts during debug. Or does it only break it when signing is disabled?

**Review by waydabber — DISMISSED** [review]

**Comment by JoniVR** [comment]
It doesn't break it at all, I didn't realise you needed to use modifiers to set the shortcuts for a brief moment.. let's call it.. not enough sleep 😂

**Comment by waydabber** [comment]
> It doesn't break it at all, I didn't realise you needed to use modifiers to set the shortcuts for a brief moment.. let's call it.. not enough sleep 😂

lol ok. 😂 Let's merge it then!

**Comment by waydabber** [comment]
But wait, the Quit application fix is not complete! You need to change all appliation-s, not only the comments!
Screen Shot 2021-10-01 at 23 28 11

**Comment by JoniVR** [comment]
I noticed after the conflicts 😁 done

**Review by waydabber — APPROVED** [review]

**Pull request merged**
