### PR TITLE
Fix Intel DDC Swift optimization issue

### PR DESCRIPTION
**Pull request by waydabber**

### CODE REVIEW

**Review by JoniVR — APPROVED** [review]
I would await some further testing from @the0neyouseek and perhaps others to be certain, but in my testing everything was working fine! Once again, great work! 

<details>
<summary>fix branch</summary>

```
2021-09-05 22:08:35.128244+0200 MonitorControl[66729:3117079] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600002d61920> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2021-09-05 22:08:35.206720+0200 MonitorControl[66729:3117079] Reading Accessibility privileges - Current access status true
2021-09-05 22:08:35.206798+0200 MonitorControl[66729:3117079] Request for updateDisplay with reconfigreID 0
2021-09-05 22:08:35.211525+0200 MonitorControl[66729:3117079] Using CGSServiceForDisplayNumber to acquire framebuffer port for 459121749.
2021-09-05 22:08:35.212225+0200 MonitorControl[66729:3117079] kIOI2CSimpleTransactionType is supported.
2021-09-05 22:08:35.213686+0200 MonitorControl[66729:3117079] Supported display found: Color LCD (Vendor: 1552, Model: 1552)
2021-09-05 22:08:35.218826+0200 MonitorControl[66729:3117079] Supported display found: 38GN950 (Vendor: 7789, Model: 7789)
2021-09-05 22:08:35.221680+0200 MonitorControl[66729:3117079] Polling 5 times
2021-09-05 22:08:35.234825+0200 MonitorControl[66729:3117079] 38GN950 (MonitorControl.Command.audioSpeakerVolume):
2021-09-05 22:08:35.234865+0200 MonitorControl[66729:3117079]  - current value: 39 - from display? true
2021-09-05 22:08:35.234884+0200 MonitorControl[66729:3117079]  - maximum value: 100 - from display? true
2021-09-05 22:08:35.234908+0200 MonitorControl[66729:3117079]  - current ddc value: unknown
2021-09-05 22:08:35.234919+0200 MonitorControl[66729:3117079]  - stored maximum ddc value: 100
2021-09-05 22:08:35.237743+0200 MonitorControl[66729:3117079] Polling 5 times
2021-09-05 22:08:35.249985+0200 MonitorControl[66729:3117079] 38GN950 (MonitorControl.Command.luminance):
2021-09-05 22:08:35.250011+0200 MonitorControl[66729:3117079]  - current value: 50 - from display? true
2021-09-05 22:08:35.250025+0200 MonitorControl[66729:3117079]  - maximum value: 100 - from display? true
2021-09-05 22:08:50.970566+0200 MonitorControl[66729:3117079] Metal API Validation Enabled
2021-09-05 22:08:51.012230+0200 MonitorControl[66729:3117079] MTLIOAccelDevice bad MetalPluginClassName property (null)
2021-09-05 22:08:51.013129+0200 MonitorControl[66729:3117079] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
```

</details>

<details>
<summary>master branch logs (for comparison)</summary>

```
2021-09-05 22:13:29.885849+0200 MonitorControl[67203:3123257] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000025b6cc0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2021-09-05 22:13:29.978590+0200 MonitorControl[67203:3123257] Reading Accessibility privileges - Current access status true
2021-09-05 22:13:29.978673+0200 MonitorControl[67203:3123257] Request for updateDisplay with reconfigreID 0
2021-09-05 22:13:29.992137+0200 MonitorControl[67203:3123257] Using CGSServiceForDisplayNumber to acquire framebuffer port for 459121749.
2021-09-05 22:13:29.993023+0200 MonitorControl[67203:3123257] kIOI2CSimpleTransactionType is supported.
2021-09-05 22:13:29.994946+0200 MonitorControl[67203:3123257] Supported display found: 38GN950 (Vendor: 7789, Model: 7789)
2021-09-05 22:13:30.001067+0200 MonitorControl[67203:3123257] Polling 5 times
2021-09-05 22:13:30.044631+0200 MonitorControl[67203:3123257] 38GN950 (MonitorControl.Command.audioSpeakerVolume):
2021-09-05 22:13:30.044663+0200 MonitorControl[67203:3123257]  - current value: 39 - from display? true
2021-09-05 22:13:30.044682+0200 MonitorControl[67203:3123257]  - maximum value: 100 - from display? true
2021-09-05 22:13:30.044742+0200 MonitorControl[67203:3123257]  - current ddc value: unknown
2021-09-05 22:13:30.044752+0200 MonitorControl[67203:3123257]  - stored maximum ddc value: 100
2021-09-05 22:13:30.049268+0200 MonitorControl[67203:3123257] Polling 5 times
2021-09-05 22:13:30.091651+0200 MonitorControl[67203:3123257] Checksum of reply does not match. Expected 28, got 50.
2021-09-05 22:13:30.091869+0200 MonitorControl[67203:3123257] Response was: 6E 80 BE 04 00 0D 12 18 27 16 1C
2021-09-05 22:13:30.134263+0200 MonitorControl[67203:3123257] Checksum of reply does not match. Expected 28, got 50.
2021-09-05 22:13:30.134478+0200 MonitorControl[67203:3123257] Response was: 6E 80 BE 04 00 0D 12 18 27 16 1C
2021-09-05 22:13:30.179091+0200 MonitorControl[67203:3123257] Request to interface 0 for framebuffer with ID 73223 failed.
2021-09-05 22:13:30.221596+0200 MonitorControl[67203:3123257] Reading 16 took 4 tries.
2021-09-05 22:13:30.221728+0200 MonitorControl[67203:3123257] 38GN950 (MonitorControl.Command.luminance):
2021-09-05 22:13:30.221739+0200 MonitorControl[67203:3123257]  - current value: 50 - from display? true
2021-09-05 22:13:30.221779+0200 MonitorControl[67203:3123257]  - maximum value: 100 - from display? true
2021-09-05 22:13:50.541723+0200 MonitorControl[67203:3123257] Metal API Validation Enabled
2021-09-05 22:13:50.583856+0200 MonitorControl[67203:3123257] MTLIOAccelDevice bad MetalPluginClassName property (null)
2021-09-05 22:13:50.584661+0200 MonitorControl[67203:3123257] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
```
</details>

**Comment by waydabber** [comment]
Ok, we don't have to rush this. We could even have the 3.0.0 final unoptimized and have this in 3.1.0 only but I feel the release would be more complete with this resolved.

@the0neyouseek - if you have time to test this one, please add your review and let me know if it can be merged! Thank you!

**Comment by the0neyouseek** [comment]
Hey @waydabber !
I'm sorry I won't have time to test this till next week cause I'm still away on holiday

**Comment by waydabber** [comment]
@the0neyouseek - ok, no problem! I merge it then and hopefully it works.

@JoniVR - maybe we could have a 3.0.0 final tagged temporarily as pre-release and ask for some additional feedback from those who are signed up to this issue and then change the designation to release if everything seems to work out?

**Pull request merged**
