### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Zbynius**

### CODE REVIEW

**Comment by waydabber** [comment]
Hmm. I am afraid this won't work as the translation is not added to the project file. Also some of the files seem to be regarded as binary files for some reason. If you'd like me to, I can fix this and post a new pull request about this (but it will be under my name). The other alternative is that you try to fix this.

Here is a quick tutorial on how to add the translation to the project in XCode: https://github.com/MonitorControl/MonitorControl/discussions/637#discussion-3602653

Thank you!

**Comment by Zbynius** [comment]
> Hmm. I am afraid this won't work as the translation is not added to the project file. Also some of the files seem to be regarded as binary files for some reason. If you'd like me to, I can fix this and post a new pull request about this (but it will be under my name). The other alternative is that you try to fix this.
> 
> Here is a quick tutorial on how to add the translation to the project in XCode: [#637 (comment)](https://github.com/MonitorControl/MonitorControl/discussions/637#discussion-3602653)
> 
> Thank you!

Please fix translation and add to main program.

**Comment by waydabber** [comment]
Hey @Zbynius - ok, I'll do it! Thanks for your effort and the translation files!

**Comment by waydabber** [comment]
I'll close this one and create a separate PR with the updated changes.

**Pull request closed without merging**
