### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by ozkanozcan**
Localizable.strings and Main.strings updated.
All Turkish translations were revised and translations updated in required fields.

### CODE REVIEW

**Comment by waydabber** [comment]
Hi @ozkanozcan - something seems to be wrong as the files changed are from 2019.

**Comment by JoniVR** [comment]
This is probably due to using the old fork from back when you did your original Pull Request. Steps to fix it are: 

1. Go to your fork (https://github.com/ozkanozcan/MonitorControl)
2. Open settings
3. Delete your fork
4. Fork again (Fork button top right of this page)
5. Translate using new files

Alternatively, you can also update the current fork using git, but I think just removing and re-forking will be faster.

**Comment by ozkanozcan** [comment]
> Hi @ozkanozcan - something seems to be wrong as the files changed are from 2019.
Yes, I didn't notice. There were conflicts with the 2019 files. 
I deleted the old version files. 
I will edit and send the new version

**Comment by waydabber** [comment]
Hello @ozkanozcan - I just want to let you know that I'll close this PR since @mennan completed the Turkish translation faster. I advise you to go through his translation as a peer reviewer/proofreader and feel free to improve upon it - I am sure @mennan will be delighted.

Thank you so much for your contribution!

**Pull request closed without merging**
