### PR TITLE
Volume slider checkbox

### PR DESCRIPTION
**Pull request by monoKeith**
Created a checkbox to allow hiding Volume settings.
Because some monitors (like my Dell U2718Q) doesn't support volume adjustments.

### CODE REVIEW

**Comment by monoKeith** [comment]
menugeneral
menulet

**Comment by REBELinBLUE** [comment]
Any chance of this getting merged, would be nice to hide this since I use SoundSource which intercepts the volume keys anyway

**Comment by vijaywargiya** [comment]
This would be a very good to have feature. @monoKeith you might as well remove the brightness label and just have the Monitor name with the slider underneath it. Will look cleaner.

**Comment by monoKeith** [comment]
> This would be a very good to have feature. @monoKeith you might as well remove the brightness label and just have the Monitor name with the slider underneath it. Will look cleaner.

Good idea! Will do it next week. 😊

**Comment by JoniVR** [comment]
Hi, thanks for the PR and I'm sorry for taking so long to get to this. 

I was thinking we could probably use the same UI here as we do in the keys section:
image

As some people will inevitably also ask for a "hide brightness slider" in the future (if they haven't already). This feels more consistent to me and takes up less space. Thoughts? 

Also: there's still some conflicts on this PR which will need to be resolved first.

**Comment by monoKeith** [comment]
> Hi, thanks for the PR and I'm sorry for taking so long to get to this.
> 
> I was thinking we could probably use the same UI here as we do in the keys section:
> image
> 
> As some people will inevitably also ask for a "hide brightness slider" in the future (if they haven't already). This feels more consistent to me and takes up less space. Thoughts?
> 
> Also: there's still some conflicts on this PR which will need to be resolved first.

Hi,

Yes I think it's a good idea to be able to configure both brightness and volume slider.

Do you think it's better if this is a general option for all displays?
Or make it an option for each display (maybe put 2 checkbox under "Display" menu alongside with "Enabled")?

**Comment by JoniVR** [comment]
Hmm it might be better to allow it for each display, however the display menu is already pretty wide.. 

I think in the future we'd probably be better off switching dual pane preferences style like Xcode uses for a view like this:

image

In this case we could put the displays with name left and the details in a reusable view on the right. I would understand it if you think this is a little bit out-of-scope for this PR, so we can always just add it now and redesign the preferences pane later.

What does everyone else think about this? Any other suggestions?

**Comment by JoniVR** [comment]
Hi, thanks for the PR, however this has now been added in v3.0.0 and will be part of the next beta, so I'd rather just release it with v3.0.0 in the future. Your time and effort however is much appreciated and I'm sorry we didn't get to merging this.

image

**Pull request closed without merging**
